### ISSUE TITLE
Add Hyperquque

### ISSUE THREAD

**Issue by kjrstory** [trevor-vincent/awesome-high-performance-computing#6]
This is a new scheduler HyperQueue.
https://github.com/It4innovations/hyperqueue
I'm still not quite sure how this scheduler differs from or competes with traditional Slurm/PBS. 
Interestingly, HQ can even run on Slurm/PBS.
I need to judge whether this scheduler has matured enough, and if it turns out to be awesome, it might be good to register it this list.

**Comment by trevor-vincent** [comment]
This is an awesome scheduler, I added it. Thank you so much for the find.
