### ISSUE TITLE
Add new wiki

### ISSUE THREAD

**Issue by imjustleaving** [trevor-vincent/awesome-high-performance-computing#7]
Hi! Thanks for adding my site Servers@Home. I also have a wiki [https://wiki.hydrology.cc/en/home](https://wiki.hydrology.cc/en/home) that I wanted to bring to your attention if you feel like it is something that belongs here. Thanks again!

**Comment by trevor-vincent** [comment]
Awesome, great work! I'll add it to wikis section.
